config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :ptemples do
    member do
      post 'like'
    end
  end
  
  resources :customers, except: [:new]
  
  get '/register', to: 'customers#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :ptemples
  has_many :likes
  before_save { self.email = email.downcase}
  validates :customername, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, 
	                           uniqueness: { case_sensitive: false },
	                               format: { with: VALID_EMAIL_REGEX }
	                               
	has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
 belongs_to :customer
 belongs_to :ptemple

 validates_uniqueness_of :customer, scope: :ptemple
end

app/models/ptemple.rb
class Ptemple < ActiveRecord::Base
    belongs_to :customer
    has_many :likes
    validates :customer_id, presence: true
    validates :name, presence: true, length: { minimum: 5, maximum: 100 }
    validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
    validates :description, presence: true, length: { minimum: 20, maximum: 500 }
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> { order(updated_at: :desc) }
    
    def thumbs_up_total
      self.likes.where(like: true).size
    end
    def thumbs_down_total
      self.likes.where(like: false).size
    end
    
    private
      def picture_size
      	if picture.size > 5.megabytes
      		errors.add(:picture, "should be less than 5MB")
      	end
      end   
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

 def current_user
  @current_user ||= Customer.find(session[:customer_id]) if session[:customer_id]
 end

 def logged_in?
  !!current_user
 end
 
 def require_user
  if !logged_in?
 	 flash[:danger] = "You must logged in to perform the action"
 	 redirect_to :back
  end
 end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update] 
   
  def index
   @customers = Customer.paginate( page: params[:page], per_page: 1)
  end

  def new
   @customer = Customer.new 
  end
  
  def create
	@customer = Customer.new(customer_params)
   if @customer.save
	flash[:success] = "Your account has been created succesfully"
 	session[:customer_id] = @customer.id
	redirect_to ptemples_path
   else
	render'new'
   end
  end
  
  def edit
# 	@customer = Customer.find(params[:id])
  end

  def update
# 	@customer = Customer.find(params[:id])
	if @customer.update(customer_params)
		flash[:success] = "Your profile has been updated succesfully"
		redirect_to customer_path(@customer)
	else
		render'edit'
	end
  end

  def show
#   @customer = Customer.find(params[:id])
   @ptemples = @customer.ptemples.paginate( page: params[:page], per_page: 3)
  end
private
  def customer_params
	params.require(:customer).permit(:customername, :email, :password)
  end
  
  def set_customer
    @customer = Customer.find(params[:id])
  end 
  
  def require_same_user
	if current_user != @customer
		flash[:danger] = "You can only edit your own profile"
		redirect_to root_path
	end
  end
   
   
    
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

 def new
 end
 
 def create
  customer = Customer.find_by(email: params[:email])
  if customer && customer.authenticate(params[:password])
   	session[:customer_id] = customer.id
   	flash[:success] = "You are logged in"
   	redirect_to ptemples_path
  else
   	flash.now[:danger] = "Your email address or password doesnot match"
   	render 'new'
  end
 end
 
 def destroy
  session[:customer_id] = nil
  flash[:success] = "You have logged out"
  redirect_to root_path
 end

 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
         redirect_to ptemples_path if logged_in?
    end
    
end

app/controllers/ptemples_controller.rb
class PtemplesController < ApplicationController
 before_action :set_ptemple, only: [:edit, :update, :show, :like]
 before_action :require_user, except: [:show, :index]
 before_action :require_same_user, only: [:edit, :update]
 
 def index
   @ptemples = Ptemple.paginate( page: params[:page], per_page: 3)
 end

 def show
   # @ptemple = Ptemple.find(params[:id])
 end

 def new
  @ptemple = Ptemple.new
 end

 def create
  @ptemple = Ptemple.new(ptemple_params)
  @ptemple.customer = current_user

  if @ptemple.save
    flash[:success] = "Temple was created successfully!"
    redirect_to ptemples_path
  else
  	render :new
  end
 end
 
 def edit
   # @ptemple = Ptemple.find(params[:id])
 end

 def update
  # @ptemple = Ptemple.find(params[:id])
   if @ptemple.update(ptemple_params)
    flash[:success] = "Temple was updated successfully!"
    redirect_to ptemple_path(@ptemple)
   else
 	render :edit
   end
 end
 
 def like
  # @ptemple = Ptemple.find(params[:id])
  like = Like.create(like: params[:like], customer: current_user, ptemple: @ptemple)
  if like.valid?
   flash[:success] = "Your selection was successful"
   redirect_to :back
  else
	  flash[:danger] = "You can only like/dislike once"
	  redirect_to :back
  end
 end

 private
   def ptemple_params
    params.require(:ptemple).permit(:name, :summary, :description, :picture)
   end
   
   def set_ptemple
    @ptemple = Ptemple.find(params[:id])
   end

   def require_same_user
     if current_user != @ptemple.customer 
     flash[:danger] = "You can only edit your own profile"
     redirect_to ptemples_path
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
def gravatar_for(customer, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(customer.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	image_tag(gravatar_url, alt:customer.customername, class: "gravatar")
end
	   
    
end

app/views/customers/_form.html.erb
<%= render 'shared/errors', obj: @customer %>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @customer do |f| %>   
		
		    <%= f.label :name %>
		    <%= f.text_field :customername %>
        
        <%= f.label :email %>
        <%= f.email_field :email %> 

        <%= f.label :password %>
        <%= f.password_field :password %>


        <%= f.submit(@customer.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
     <% end %>    
	</div>
</div>

app/views/customers/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form' %>

app/views/customers/index.html.erb
<%= render 'shared/page_title', title: "ALL Names" %>
<ul class="nav nav-tabs">
  <li> <%= link_to "Temples", ptemples_path %> </li>
  <li class="active"> <%= link_to "Subscribers", customers_path %> </li>
  
</ul>



<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= will_paginate %>
	</div>
</div>

<% @customers.each do |customer| %>
  <div class="row">
  	<div class="col-md-4 col-md-offset-4 center">
       <%= link_to gravatar_for(customer, size: 200), customer_path(customer) %>
       <p>
          <h5>Customer name: <%=customer.customername %></h5> 
       </p>  		

    </div>
  </div>
<% end %>

app/views/customers/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>

<%= render 'form' %>

app/views/customers/show.html.erb
<%= render 'shared/page_title', title: "Customer: " + @customer.customername %>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @customer, size: 200 %>
		<hr/>
	</div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <h3><em>Temples:</em></h3>
        <%= will_paginate @ptemples %>
    </div>
</div>

<% @ptemples.each do |ptemple| %>
<div class="row">
	<div class="col-lg-6 well col-lg-offset-3">
    <h4><%= link_to ptemple.name, ptemple_path(ptemple) %></h4>
      <p><%= ptemple.summary %></p>
      <p>
        <span class='quiet'><small> created: <%= time_ago_in_words(ptemple.created_at)%> ago, </small></span>
        <span class='quiet'><small> updated: <%= time_ago_in_words(ptemple.updated_at)%> ago,</small></span>
       </p>
     <div class="pull-right">
        <%= link_to like_ptemple_path(ptemple, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= ptemple.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_ptemple_path(ptemple, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= ptemple.thumbs_down_total %>
        <% end %> 

      </div>
    </div>
    </div>
    <% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
     <p>&copy; CITYGUIDE_by_satya 2016</p>
 </div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
		  <div class="alert alert-<%= message_type %>"><%= message %>
		    <a class="close" data-dismiss="alert">&#215;</a> 
		    </div>
		<% end%>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "CITYGUIDE", root_path, class: "btn tbn-lg btn-success" , id: "logo" %>
    
    <div class="nav_item">
      <%= link_to "PURI", ptemples_path, class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav_item">
      <%= link_to "Link1", "", class: "btn btn-default btn-warning" %>
    </div>
    
    <% if logged_in? %>
    <div class="nav_item">
      <%= link_to "New Temple", new_ptemple_path, class: "btn btn-default btn-warning" %>
    </div>

        <ul class="nav_item">
            <li class="dropdown">
              <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
                <%= current_user.customername %> <b class="caret"></b>
                <% end %>
            <ul class="dropdown-menu">
                <li><%= link_to "View Profile", customer_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_customer_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", logout_path %></li>
            </ul> 
            </li>
        </ul>
        <% else %>
         <div class="nav_item">
         <%= link_to "Log in", login_path, class: "btn btn-default btn-success" %>
        </div>
        <% end %>
  </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CITYGUIDE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
 <div class="container">
 <%= render 'layouts/messages' %>
<%= yield %>

<%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>

<div class="row">
	<div class="well col-md-6 col-md-offset-3">
		<%= form_tag '/login' do %>
            
            <%= label_tag :email %>
            <%= text_field_tag :email %>

            <%= label_tag :password %>
            <%= password_field_tag :password %>

            <%= submit_tag 'Login', class: 'btn btn-success' %>
        
		<% end %>
	</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome To Religious Places</h1>
	<h2>
	  A hands on guide
	 </h2>
	<%= link_to "Sign up now!", register_path , class: "btn btn-lg btn-success" %>
</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="midrow">
			View  as Guest User
		</h3>
		<h2 class="left">Browse and view as a guest and Sign up later</h2>
		<p><%= link_to "Browse  Listings", ptemples_path, class: "btn btn-warning btn-small" %></p>
	</div>
	<div class="col-lg-4">
		<h3 class="midrow">
			Sign in to your account
		</h3>
		<h2 class="left">Add/update your create reviews/like-dislike </h2>
		<p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
	</div>
	<div class="col-lg-4">
		<h3 class="midrow">
			View as Guest User
		</h3>
		<h2 class="left">Browse and view as a guest and Sign up later</h2>
		<p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
	</div>
</div>

app/views/ptemples/_form.html.erb
<%= render 'shared/errors', obj: @ptemple %>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for(@ptemple, html: { multipart: true }) do |f| %>   
		
		    <%= f.label :name %>
		    <%= f.text_field :name %>
        
        <%= f.label :summary %>
        <%= f.text_field :summary %> 

        <%= f.label :description %>
        <%= f.text_area :description, rows: 10 %>

        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>    
        </span>


        <%= f.submit(@ptemple.new_record? ? 'Create Temple' : 'Edit Temple', class: "btn btn-success") %>
     <% end %>    
	</div>
</div>

<script type="text/javascript">
    $('#ptemple_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a small file')
        }
    });
</script>

app/views/ptemples/edit.html.erb
<%= render 'shared/page_title', title: "Edit Temple" %>

<%= render 'form' %>

app/views/ptemples/index.html.erb
<%= render 'shared/page_title', title: "PURI" %>
<ul class="nav nav-tabs">
  <li class="active"> <%= link_to "Temples", ptemples_path %> </li>
  <li><%= link_to "Subscribers", customers_path %> </li>
</ul>

<%= will_paginate %>

 <% @ptemples.each do |ptemple| %>
  <div class="row">
  	<div class="col-md-2">
  		<section class="customer_info center">
  		  <%= link_to gravatar_for(ptemple.customer, size: 100), customer_path(ptemple.customer) %>
        <h5>name: <%= ptemple.customer.customername %></h5>
  		</section>
  	</div>
    
    <div class="col-lg-6 well">
        <h4><%= link_to ptemple.name, ptemple_path(ptemple) %></h4>
        <p><%= ptemple.summary %></p>
        <p>
            <span class='quiet'><small> created: <%= time_ago_in_words(ptemple.created_at)%> ago, </small></span>
            <span class='quiet'><small> updated: <%= time_ago_in_words(ptemple.updated_at)%> ago</small></span>
        </p>
        	 <div class="pull-right">
	   	      <%= link_to like_ptemple_path(ptemple, like: true), method: :post do %>
	   	        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= ptemple.thumbs_up_total %>
	   	      <% end %> &nbsp&nbsp&nbsp&nbsp
            <%= link_to like_ptemple_path(ptemple, like: false), method: :post do %>
              <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= ptemple.thumbs_down_total %>
	   	       <% end %>	
	   	     </div>
        
    </div>
    
    <div class="col-md-4">
      <%= image_tag(ptemple.picture.url, size: "250x150", class: "gravatar") if ptemple.picture? %> 
    </div>

    </div>
    <hr/>
  <% end %>
    
<%= will_paginate %>

app/views/ptemples/new.html.erb
<%= render 'shared/page_title', title: "Create a new Temple" %>

<%= render 'form' %>

app/views/ptemples/show.html.erb
<%= render 'shared/page_title', title: @ptemple.name %>
<div class="row">
	<div class="col-md-4 pull-right center">
		<%= link_to gravatar_for(@ptemple.customer, size: 200), customer_path(@ptemple.customer) %>
		<p>
		  <h5>Brought to you by: <%= @ptemple.customer.customername %></h5>
		</p>
	</div>
	<div class="col-md-8">
		<% if logged_in? and @ptemple.customer == current_user %>
	    <%= link_to "Edit this Temple", edit_ptemple_path(@ptemple), class: "btn btn-success pull-right" %>
	    <% end %>
	    <h3><%= @ptemple.summary %></h3>
	      <div class="show_ptemple">
	  	   <%= image_tag(@ptemple.picture.url, class: "gravatar") if @ptemple.picture? %>  <!-- addition of imagetag -->
	      </div>
	    <div class="well">
	   	  <p>
	   	  <strong>Steps:</strong>
	   	  </p>
	   	  <%= simple_format(@ptemple.description) %>
	   	  
	   	    <div class="pull-right">
	   	       <%= link_to like_ptemple_path(@ptemple, like: true), method: :post do %>
	   	        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @ptemple.thumbs_up_total %>
	   	       <% end %> &nbsp&nbsp&nbsp&nbsp
              <%= link_to like_ptemple_path(@ptemple, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @ptemple.thumbs_down_total %>
	   	      <% end %>	
	   	    </div>
	   	  
	   	 </div>
	</div>
</div>
<h5><%= link_to "Return to Temples Listing", ptemples_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
  	<div class="alert alert-danger col-md-8 col-md-offset-2">
  		<h5>Please correct the following errors:</h5>
  		<ul>
  		  <% obj.errors.full_messages.each do |msg| %>
  		   <li><%= msg %></li>
  		  <% end %>
  		  </ul>
  	</div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
	<h1><%= title %></h1>
	<hr/>
</p>